version: '3'
services:
  todoback:
    image: todobackend
    restart: unless-stopped
    ports:
      - "3001:3001"
  todofront:
    image: todofrontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - todoback
    ports:
      - "3000:3000"
  todotests:
    image: todotests
    restart: unless-stopped
    environment:
      - FRONT_HOST=todofront
    depends_on:
      - todoback
      - todofront
